repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: end-of-file-fixer
    name: fix eofs
    exclude: "^\\.version$"
  - id: mixed-line-ending
    name: fix line endings
  - id: trailing-whitespace
    name: remove trailing whitespace

- repo: local
  hooks:
  - id: black
    name: blacken code
    entry: poetry run black
    language: system
    types: [python]
  - id: isort
    name: sort python imports
    entry: poetry run isort
    language: system
    types: [python]
  - id: pylint
    name: lint python files
    entry: poetry run pylint
    language: system
    types: [python]
  - id: mypy
    name: type check python files
    entry: poetry run mypy .
    language: system
    types: [python]
    pass_filenames: false
  - id: pydocstyle
    name: lint python docstrings
    entry: poetry run pydocstyle
    language: system
    types: [python]
  - id: commitlint
    name: lint commit message
    language: system
    entry: "npx commitlint -e"
    always_run: true
    stages: [commit-msg]
  - id: test
    name: run unittests
    language: system
    entry: "pipx run tox run -v"
    types: [python]
    pass_filenames: false
  - id: docs
    name: build docs with sphinx
    language: system
    files: ".*\\.py|docs/make\\.sh"
    exclude: "tests/.*\\.py"
    entry: poetry run docs/make.sh
    pass_filenames: false
  - id: cspell
    name: spell check docs
    language: system
    files: "docs/.*\\.md"
    entry: "npx cspell"
