site_name: "corgy"
site_url: "https://jkoushik.me/corgy"
repo_url: "https://github.com/jayanthkoushik/corgy"
site_description: "Documentation for Python package 'corgy'."
site_author: "Jayanth Koushik"
copyright: "Copyright (c) 2021-2023 Jayanth Koushik"

docs_dir: "docs/www"
site_dir: "_site"

nav:
  - "Home": "index.md"
  - "Usage":
      - "corgy": "usage/corgy.md"
      - "corgy.types": "usage/corgy.types.md"

plugins:
  - search
  - offline
  - mike:
      canonical_version: "latest"
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: "#"

extra:
  version:
    provider: mike

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.expand
  icon:
    logo: "material/dog-side"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"
