name: Create GitHub release with changelog and wheel

on:
  push:
    tags:
    - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install poetry
      run: pipx install poetry
    - name: Install poetry-dynamic-versioning
      run: pipx install poetry-dynamic-versioning
    - name: Create lock file
      run: poetry lock
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: poetry
    - uses: actions/setup-node@v3
    - name: Run conventional-github-releaser
      run: npx conventional-github-releaser -p angular
      env:
        CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.CONVENTIONAL_GITHUB_RELEASER_TOKEN }}
    - name: Build dist
      run: poetry build
    - name: Add wheel to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.whl
        tag: ${{ github.ref }}
        file_glob: true
