name: Publish package to pypi

on:
  push:
    tags:
    - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install poetry
      run: python -m pip install poetry
    - name: Install poetry-dynamic-versioning
      run: python -m pip install poetry-dynamic-versioning
    - name: Build dist
      run: python -m poetry build
    - name: Publish to pypi
      run: python -m poetry publish -u __token__ -p $PYPI_TOKEN
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
