name: Run tests

on:
  push:
    branches:
    - master
    paths:
    - '**.py'
    - 'pyproject.toml'
    - '.github/workflows/test-package.yml'

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Create lock file
      run: poetry lock
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: poetry
    - name: Install required dependencies
      run: poetry install --only main
    - name: Run core tests
      run: poetry run python -m unittest
    - name: Install extra dependencies
      run: poetry install --only main -E colors -E toml
    - name: Run all tests
      run: poetry run python -m unittest
      env:
        PYTHONDEVMODE: 1
