name: Run tests

on:
  push:
    branches:
    - master
    paths:
    - '**.py'
    - 'pyproject.toml'
    - '.github/workflows/test-package.yml'

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
    - name: Install dependencies
      run: $HOME/.local/bin/poetry install --no-dev -E colors
    - name: Run tests
      run: $HOME/.local/bin/poetry run python -m unittest
      env:
        PYTHONDEVMODE: 1
